name: docs
on:
  push:
    branches:
    - master

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install requirements
      run: |
        pip3 install -U sphinx
        pip3 install sphinx-rtd-theme
        pip3 install scipy==1.12.0
        pip3 install scikit-learn==1.1.3
    
    - name: Build docs
      run: |
        pip3 install .
        cd docs
        sphinx-apidoc -o . ../kan
        make clean html
        make html
    # https://github.com/peaceiris/actions-gh-pages
    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/
